/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IdeaAuto: typeof import('./src/components/ideaAuto.vue')['default']
    IdeaFromPaper: typeof import('./src/components/ideaFromPaper.vue')['default']
    InputIdea: typeof import('./src/components/inputIdea.vue')['default']
    MethodFromPaper: typeof import('./src/components/methodFromPaper.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    PageFooter: typeof import('./src/components/pageFooter.vue')['default']
  }
}
